In [2]:
import numpy as np
a = np.array([[1,2,3],[0,1,4]])

print(a.size)

6


In [5]:
import numpy as np
a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)

d = a + b + c
print(d)

print(d[1,2])


[[2 3 4]
 [1 2 5]]
5


In [1]:
import numpy as np
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = np.dot(A, B)
print(C)

[[ 36 -12]
 [ -1   2]]


In [2]:
import numpy as np
A = np.array([[1, 4, 5, 12, 14], 
              [-5, 8, 9, 0, 17], 
              [-6, 7, 11, 19, 21]])
print(A[:,2:4])


[[ 5 12]
 [ 9  0]
 [11 19]]


In [3]:
a=np.array([1,1,1,1,1])
b=np.array([2,2,2,2,2])
a*b


array([2, 2, 2, 2, 2])

In [4]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)


0

In [5]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)


0

In [7]:
a = np.array([1, 1, 1, 1, 1])
a += 10
print(a)

[11 11 11 11 11]


In [8]:
import numpy as np

a = np.array([[0, 1, 0], [1, 0, 1]])
a += 3
b = a + 3
print(a[1,2] + b[1,2])


11
